export const DEMO_CASE = {
  case_id: 'case_northdock_001',
  case_title: 'Evening Outbound Pressure — NorthDock Hub',
  facility_name: 'NorthDock Fulfillment Hub',
  facility_type: 'E-commerce fulfillment centre',
  shift_name: 'Evening outbound pressure shift',
  business_objective: 'Protect premium carrier cutoff while preventing next-wave replenishment collapse',
  current_pressure_level: 'CRITICAL',
  shift_start_time: '16:00',
  shift_end_time: '22:00',
  decision_deadline: '90 minutes before carrier cutoff',
  available_workers: '7',
  worker_skill_summary: '4 pickers, 1 replenishment-trained worker, 1 exception handler, 1 dock staging lead',
  equipment_constraints: '2 working pallet jacks, 1 scanner pool degraded, cold-chain staging area near capacity',
  supervisor_notes: 'Outbound queue is late, but blocked SKUs may stall the next wave.',
  current_operational_hypothesis: 'A pure outbound push may protect immediate SLAs but create a hidden replenishment failure.',
};

export const DEMO_SNAPSHOT = {
  snapshot_id: 'snap_001',
  snapshot_title: 'Evening Shift Opening Snapshot',
  facility_zone_summary: 'Outbound: overloaded, Inbound: moderate, Replenishment: blocked SKUs detected, Staging: near capacity, Dock: 2 trucks waiting',
  active_orders_summary: '142 orders pending, 38 premium, 12 cold-chain',
  staffing_summary: '7 workers available, 4 pickers, 1 replenishment, 1 exception, 1 dock',
  equipment_status: '2 pallet jacks operational, 1 scanner pool degraded, cold-chain staging at 85% capacity',
  current_bottlenecks: 'Blocked SKUs in replenishment queue, scanner degradation slowing pick rate',
  carrier_cutoff_summary: 'Premium carrier cutoff in 90 minutes, standard carrier cutoff in 3 hours',
  SLA_pressure_summary: '38 premium orders at risk of missing cutoff, 12 cold-chain orders time-sensitive',
  safety_or_fatigue_notes: 'Workers entering hour 4 of shift, no fatigue flags yet',
  source_url: 'https://example.com/northdock/snapshot/evening-001',
  source_hash: 'a1b2c3d4e5f6',
};

export const DEMO_TASKS = [
  {
    task_id: 'task_001',
    task_title: 'Pick and pack premium outbound orders',
    task_type: 'PICKING',
    department: 'Outbound',
    deadline: '90 minutes',
    SLA_impact: 'HIGH',
    customer_priority: 'PREMIUM',
    estimated_effort: '4 workers x 90 min',
    required_skill: 'Picker',
    required_equipment: 'Scanner, pallet jack',
    dependency: 'Replenishment of blocked SKUs',
    delay_risk: 'Carrier cutoff miss, premium SLA breach',
    safety_note: 'None',
    status_at_submission: 'PENDING',
  },
  {
    task_id: 'task_002',
    task_title: 'Unblock replenishment queue',
    task_type: 'REPLENISHMENT',
    department: 'Replenishment',
    deadline: '60 minutes',
    SLA_impact: 'MEDIUM',
    customer_priority: 'INTERNAL',
    estimated_effort: '1 worker x 60 min',
    required_skill: 'Replenishment-trained',
    required_equipment: 'Pallet jack',
    dependency: 'None',
    delay_risk: 'Next picking wave collapses',
    safety_note: 'Heavy lifting involved',
    status_at_submission: 'PENDING',
  },
  {
    task_id: 'task_003',
    task_title: 'Resolve exception orders',
    task_type: 'EXCEPTION',
    department: 'Exceptions',
    deadline: '120 minutes',
    SLA_impact: 'MEDIUM',
    customer_priority: 'MIXED',
    estimated_effort: '1 worker x 120 min',
    required_skill: 'Exception handler',
    required_equipment: 'Scanner',
    dependency: 'None',
    delay_risk: 'Backlog grows, blocks future orders',
    safety_note: 'None',
    status_at_submission: 'PENDING',
  },
  {
    task_id: 'task_004',
    task_title: 'Stage dock for carrier pickup',
    task_type: 'STAGING',
    department: 'Dock',
    deadline: '75 minutes',
    SLA_impact: 'HIGH',
    customer_priority: 'PREMIUM',
    estimated_effort: '1 worker x 75 min',
    required_skill: 'Dock staging lead',
    required_equipment: 'Pallet jack',
    dependency: 'Outbound picking completion',
    delay_risk: 'Truck departure delay',
    safety_note: 'Dock area, PPE required',
    status_at_submission: 'PENDING',
  },
  {
    task_id: 'task_005',
    task_title: 'Cold-chain dispatch',
    task_type: 'DISPATCH',
    department: 'Cold-chain',
    deadline: '60 minutes',
    SLA_impact: 'CRITICAL',
    customer_priority: 'PREMIUM',
    estimated_effort: '1 worker x 45 min',
    required_skill: 'Picker',
    required_equipment: 'Cold-chain staging area',
    dependency: 'Cold-chain staging capacity',
    delay_risk: 'Spoilage risk, compliance breach',
    safety_note: 'Temperature-sensitive handling',
    status_at_submission: 'PENDING',
  },
];

export const DEMO_PLANS = [
  {
    plan_id: 'plan_1',
    plan_title: 'Full Outbound Push',
    labor_allocation_summary: 'All 7 workers to outbound picking and staging',
    workers_assigned_by_function: '6 pickers, 1 dock staging',
    priority_task_order: 'Premium outbound → cold-chain → standard outbound → dock staging',
    tasks_to_delay: 'Replenishment, exceptions, inbound sorting',
    expected_upside: 'Maximum chance of meeting premium carrier cutoff',
    key_operational_risks: 'Replenishment queue stays blocked, next picking wave collapses',
    bottleneck_assumptions: 'Assumes blocked SKUs do not affect current wave',
    SLA_assumptions: 'Assumes all premium orders can be picked in 90 minutes',
    safety_or_fatigue_assumptions: 'Workers may fatigue by hour 6 without rotation',
    failure_conditions: 'If blocked SKUs affect current wave, picking stalls mid-shift',
  },
  {
    plan_id: 'plan_2',
    plan_title: 'Bottleneck-Aware Split',
    labor_allocation_summary: '4 workers to outbound, 1 to replenishment, 1 to exceptions, 1 to dock',
    workers_assigned_by_function: '4 pickers (outbound), 1 replenishment, 1 exception handler, 1 dock staging',
    priority_task_order: 'Premium outbound + replenishment unblock simultaneously → cold-chain → exceptions → dock',
    tasks_to_delay: 'Low-priority inbound sorting, cycle counts, non-urgent staging cleanup',
    expected_upside: 'Protects near-term SLA while preventing next-wave collapse',
    key_operational_risks: 'Fewer pickers on outbound, slightly higher risk of cutoff miss',
    bottleneck_assumptions: 'Blocked SKUs will affect next wave if not resolved now',
    SLA_assumptions: '4 pickers can handle premium volume in 90 minutes',
    safety_or_fatigue_assumptions: 'Workload is distributed, fatigue risk is lower',
    failure_conditions: 'If premium volume exceeds 4-picker capacity, cutoff is missed',
  },
  {
    plan_id: 'plan_3',
    plan_title: 'Replenishment First',
    labor_allocation_summary: '3 workers to replenishment, 2 to outbound, 1 to cold-chain, 1 to dock',
    workers_assigned_by_function: '3 replenishment, 2 pickers, 1 cold-chain, 1 dock',
    priority_task_order: 'Replenishment unblock → cold-chain → premium outbound → dock',
    tasks_to_delay: 'Exceptions, standard outbound, inbound',
    expected_upside: 'Prevents total next-wave collapse, protects cold-chain',
    key_operational_risks: 'Premium carrier cutoff almost certainly missed',
    bottleneck_assumptions: 'Replenishment is the true bottleneck, not picking speed',
    SLA_assumptions: 'Accepts premium SLA breach to protect operational continuity',
    safety_or_fatigue_assumptions: 'Heavy replenishment work may cause fatigue',
    failure_conditions: 'Premium customers escalate, carrier relationship damaged',
  },
];

export const DEMO_EVIDENCE = [
  {
    evidence_id: 'ev_001',
    evidence_title: 'Real-time order queue export',
    evidence_type: 'DATA_EXPORT',
    evidence_url: 'https://example.com/northdock/orders/export-evening',
    evidence_hash: 'e1f2a3b4c5d6',
    source_name: 'NorthDock WMS',
    source_credibility_note: 'Direct system export, high reliability',
    relevance_to_operational_question: 'Shows exact premium order count and deadlines',
    related_task_ids: 'task_001,task_005',
    related_labor_plan_ids: 'plan_1,plan_2',
    evidence_category: 'ORDER_DATA',
  },
  {
    evidence_id: 'ev_002',
    evidence_title: 'Blocked SKU inventory report',
    evidence_type: 'INVENTORY_REPORT',
    evidence_url: 'https://example.com/northdock/inventory/blocked-skus',
    evidence_hash: 'f7g8h9i0j1k2',
    source_name: 'NorthDock Inventory System',
    source_credibility_note: 'System-generated, updated 15 minutes ago',
    relevance_to_operational_question: 'Confirms replenishment queue is blocked by 8 SKUs',
    related_task_ids: 'task_002',
    related_labor_plan_ids: 'plan_2,plan_3',
    evidence_category: 'INVENTORY_DATA',
  },
  {
    evidence_id: 'ev_003',
    evidence_title: 'Carrier cutoff schedule',
    evidence_type: 'CARRIER_SCHEDULE',
    evidence_url: 'https://example.com/northdock/carriers/cutoff-schedule',
    evidence_hash: 'l3m4n5o6p7q8',
    source_name: 'Carrier Portal',
    source_credibility_note: 'Official carrier schedule, confirmed today',
    relevance_to_operational_question: 'Premium carrier departs in 90 minutes, no flexibility',
    related_task_ids: 'task_001,task_004',
    related_labor_plan_ids: 'plan_1,plan_2',
    evidence_category: 'CARRIER_DATA',
  },
];
